### ISSUE TITLE
makepkg doesn't detect reference to (`cygpath -m /`|`cygpath -w /`) in *.cmake files.

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/msys2-pacman#14]

**Comment by jeremyd2019** [comment]
Please attach an example of such a file that was not detected.  The only thing I can figure is that `grep` thinks it's binary.  Maybe the files are encoded in UTF-16 or something.

**Comment by MehdiChinoune** [comment]
I have encountered this issue with mingw-w64-itk package after trying to comment the part where it fixes *.cmake files.
https://github.com/MehdiChinoune/MINGW-packages/commit/281ba3f9dbb1f9dbe1c878cf665525fbce30319e
https://github.com/MehdiChinoune/MINGW-packages/runs/5673705864?check_suite_focus=true#step:9:6974

**Comment by MehdiChinoune** [comment]
```
$ file -i ITK/*.cmake
ITK/ITKConfig.cmake:          text/plain; charset=us-ascii
ITK/ITKConfigVersion.cmake:   text/plain; charset=us-ascii
ITK/ITKModuleAPI.cmake:       text/plain; charset=us-ascii
ITK/ITKTargets-release.cmake: text/plain; charset=us-ascii
ITK/ITKTargets.cmake:         text/plain; charset=us-ascii
ITK/UseITK.cmake:             text/plain; charset=us-ascii
```
