### ISSUE TITLE
pacman -Qkk doesn't work

### ISSUE THREAD

**Issue by lazka** [msys2/msys2-pacman#15]
I don't think it ever has:

```
> pacman -Qkk bash
warning: bash: /usr/bin/bash.exe (SHA256 checksum mismatch)
warning: bash: /usr/bin/bashbug (SHA256 checksum mismatch)
warning: bash: /usr/bin/sh.exe (SHA256 checksum mismatch)
warning: bash: /usr/share/doc/bash/CHANGES (SHA256 checksum mismatch)
warning: bash: /usr/share/doc/bash/COMPAT (SHA256 checksum mismatch)
warning: bash: /usr/share/doc/bash/FAQ (SHA256 checksum mismatch)
warning: bash: /usr/share/doc/bash/INTRO (SHA256 checksum mismatch)
warning: bash: /usr/share/doc/bash/NEWS (SHA256 checksum mismatch)
warning: bash: /usr/share/doc/bash/POSIX (SHA256 checksum mismatch)
warning: bash: /usr/share/doc/bash/RBASH (SHA256 checksum mismatch)
...
```

The man page also says it checks permissions and modification dates.

**Comment by elieux** [comment]
Problem is that our _bsdtar_ doesn't support computing SHA256, so our packages don't even have that checksum. I'm trying to fix the _bsdtar_ issue on two fronts, but the checksums will only start appearing in newly built packages.

**Comment by elieux** [comment]
Fix for _libarchive_'s integration with WinCrypto: https://github.com/libarchive/libarchive/pull/1724

Switch for our _libarchive_ build to link with OpenSSL: https://github.com/msys2/MSYS2-packages/pull/2934

**Comment by lazka** [comment]
I guess we can close this now.

I started rebuilding all of "base" so we can run "pacman -Qkk" in CI when building the installer, but it's only half way done.

thanks again
