### ISSUE TITLE
pacman-msys2 doesn't strip static libraries (archives)

### ISSUE THREAD

**Issue by MehdiChinoune** [msys2/msys2-pacman#7]
Looking at https://github.com/msys2/msys2-pacman/blob/msys2-v6.0.1/scripts/libmakepkg/tidy/strip.sh.in#L204, It looks like pacman doesn't strip archives `application/x-archive`

Edit: They were stripped before upgrading to pacman 6.0
see: https://github.com/msys2/msys2-pacman/blob/msys2-v5.2.2/scripts/libmakepkg/tidy/strip.sh.in#L187

**Comment by lazka** [comment]
thanks
